version: "3"

services:
  db:
    platform: linux/amd64
    container_name: bank-transactions-db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - 'expenses-db:/var/lib/mysql'

volumes:
  expenses-db:
    driver: local
